[tool.poetry]
name = "simple_file_sorter"
version = "0.1.2"
description = "Simple File Sorter"
authors = ["Vitalii Shishorin <moskrc@gmail.com>"]
readme = "README.md"
repository = "https://github.com/moskrc/filesorter"
keywords = ["sort", "file_sorter", "file", "sorter"]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
simple_file_sorter = "simple_file_sorter:sort"